---
require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.6
  
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - specs/**/*

Security/YAMLLoad:
  Enabled: true
  Exclude:
    - specs/**/*

Style/HashSyntax:
  Enabled: true
  Exclude:
    - Rakefile

Style/SymbolArray:
  Enabled: true
  Exclude:
    - app/db/migrations/**/*
    - Rakefile