---
development:
  DB_FILENAME: app/db/store/dev.db
  SECURE_SCHEME: HTTP
  GITHUB_ACCOUNT_URL: https://api.github.com/user

test:
  DB_FILENAME: app/db/store/test.db
  SECURE_SCHEME: HTTP
  GITHUB_ACCOUNT_URL: https://api.github.com/user

production:
  SECURE_SCHEME: HTTPS
  GITHUB_ACCOUNT_URL: https://api.github.com/user