---
development:
  DB_KEY: <`rake new_key:db`>
  MSG_KEY: <`rake new_key:msg`>
  SENDGRID_API_KEY: <provision through Heroku or SendGrid>

test:
  DB_KEY: <`rake new_key:db`>
  MSG_KEY: <`rake new_key:msg`>
  SENDGRID_API_KEY: <provision through Heroku or SendGrid>

production:
  DB_KEY: <`rake new_key:db`>
  MSG_KEY: <`rake new_key:msg`>
  SENDGRID_API_KEY: <provision through Heroku or SendGrid>