---
development:
  DB_KEY: <`rake new_key:db`>
  MSG_KEY: <`rake new_key:msg`>
  SENDGRID_URL: <`mail/send` path of appropriate API/v[?] URL>
  SENDGRID_API_KEY: <provision through Heroku or SendGrid>
  SIGNING_KEY: <`rake newkey:signing`> # only needed by client app
  VERIFY_KEY: <`rake newkey:signing`>

test:
  DB_KEY: <`rake new_key:db`>
  MSG_KEY: <`rake new_key:msg`>
  SENDGRID_URL: <`mail/send` path of appropriate API/v[?] URL>
  SENDGRID_API_KEY: <provision through Heroku or SendGrid>
  SIGNING_KEY: <`rake newkey:signing`> # only needed by client app
  VERIFY_KEY: <`rake newkey:signing`>

production:
  DB_KEY: <`rake new_key:db`>
  MSG_KEY: <`rake new_key:msg`>
  SENDGRID_URL: <`mail/send` path of appropriate API/v[?] URL>
  SENDGRID_API_KEY: <provision through Heroku or SendGrid>
  SIGNING_KEY: <`rake newkey:signing`> # only needed by client
  VERIFY_KEY: <`rake newkey:signing`>